### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by zbas** [lammpstutorials/lammpstutorials-inputs#1]
Very nice tutorial. I went through the polymer in water tutorial. I wasn't able to run the first part as I don't think the create_atoms overlap/maxtry arguments were introduced until 2022 and I have a pre-installed 2018 version. With your intermediate results included, I was able to continue.

At the very end (https://lammpstutorials.github.io/sphinx/build/html/tutorials/level2/polymer-in-water.html):
    fix myaf1 oxygen_end1 addforce ${f0} 0 0
    fix myaf2 oxygen_end2 addforce -${f0} 0 0
Should be topull1/2, I think.

If I could make a suggestion, the front page has three images and gives the impression these are the only three tutorials while actually you have more, also you can only see what the tutorials are by hovering over the picture, so people might not realise you have a tutorial relevant to them. Perhaps you could change this.

**Comment by simongravelle** [comment]
Hello, 

Thank you so much for your feedback. 

- Yes indeed, unfortunately it is impossible to make tutorials that work for all lammps version because lammps is evolving continuously. Currently, these tutorials were made compatible with the 2Aug2023 lammps version, as indicated in the top of the page. In any cases, it is great to know that you were not stuck because of that. On the side note, 2018 is quite old and I highly recommend you to upgrade, many issues have been fixed by the dev since 2018.
- Thanks for reporting, its fixed.
- You are right about the front page, but I havent found a template yet that I like that would allow to show all tutorial while also being simple & modern looking.... May be one day I will find better and change that. 

Best,
Simon
